# Generated by Django 5.1.3 on 2024-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalSite', '0002_locationmenu_offer_location_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
