# Generated by Django 5.1.3 on 2024-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalSite', '0003_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='more_information',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
