# Generated by Django 5.1.3 on 2024-12-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalSite', '0004_offer_more_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
